part1:
	g++ -o $@.out part1.cpp -lpthread 
	./$@.out input.ppm output_part1.ppm
part2_1a:
	g++  -o $@.out part2_1a.cpp -lpthread 
	./$@.out input.ppm output_part2_1a.ppm
part2_1b:
	g++  -o $@.out part2_1b.cpp -lpthread 
	./$@.out input.ppm output_part2_1b.ppm
part2_2:
	g++ -o $@.out part2_2.cpp -lpthread 
	./$@.out input.ppm output_part2_2.ppm
part2_3:
	g++ -o $@.out part2_3.cpp -lpthread 
	./$@.out input.ppm output_part2_3.ppm
clean:
	rm -f ./part*.out output_*